### ISSUE TITLE
I down can Load other Bindings

### ISSUE THREAD

**Issue by gitpower2017** [ct-Open-Source/ct-Smart-Home#11]
Hello,
I get this error message when I want to install other interfaces.

```
Failed to load node catalogue.
Check the browser console for more information
```

I created the container under QNAP with the YAML.
The containers MQTT and ZIGBee were deleted manually.

After that the container is installed in network mode Bridge

**Comment by merlinschumacher** [comment]
This might have be an upstream issue of node-red:
https://discourse.nodered.org/t/failed-to-load-node-catalogue/9796/13
