### ISSUE TITLE
user/group 1001 & 1883

### ISSUE THREAD

**Issue by poesel** [ct-Open-Source/ct-Smart-Home#12]
Both user/group 1001 & 1883 do not exist on my system. But in the startup script ownership of the nodered & mqtt directories is set to those. This creates a permissions problem later on.

Did I miss something here? I haven't any mention of these IDs anywhere in the documentation.

**Comment by merlinschumacher** [comment]
These ids are used by mqtt and nodered inside the containers. The corresponding users only exist there and are not needed on your system. if you need to edit something in there manually do it with root permissions.
