### ISSUE TITLE
Use mosquitto.conf (and pass.txt, acl.txt)

### ISSUE THREAD

**Issue by KarstenDE** [ct-Open-Source/ct-Smart-Home#14]
I try to use the `mosquitto.conf` and `pass.txt` & `acl.txt` inspired by the corresponding article in c‘t. But it does not work. I can not login with username/password.

`mosquitto.conf` already existed but was empty. So I just added the reference to `/mosquitto/data/pass.txt`.

In the docker Hub documentation it‘s described that the `mosquitto.conf` need to be mapped as a volume. But if I open a shell in the container, I can see the file at this path already.  
https://hub.docker.com/_/eclipse-mosquitto

How did you do the configuration?

**Comment by KarstenDE** [comment]
I found out, that the whole container does not start with the mosquitto.conf. With an empty one everything is working fine.

I will check the file content ...

**Comment by merlinschumacher** [comment]
I modified the config file and added the following lines:
```
allow_anonymous false
password_file /mosquitto/config/passwd
```
the passwd file is in http-basic-auth style.

What does `docker-compose logs mqtt` show for a failing container instance?

**Comment by KarstenDE** [comment]
Okay. I configured the files to `/mosquitto/data/...`

In `/mosquitto/config/...` everything works
