### ISSUE TITLE
Document versions

### ISSUE THREAD

**Issue by renne** [ct-Open-Source/ct-Smart-Home#16]
@merlinschumacher 
Please document the versions of the software used in ct-Smart-Home (e.g. node.js) in README.md for debugging purposes (e.g. [node-red-contrib-dwd-local-weather](https://github.com/c5te1n/node-red-contrib-dwd-local-weather) needs a nodejs version >= 10.0.0).

**Comment by merlinschumacher** [comment]
The next update will be moved to NodeJS 12 (and maybe there will be a variant for 10) since Node-Red now offers an official docker image. This image will just add a few nodes to the official image.

**Comment by Shaquu** [comment]
Please remember that node 12 is not LTS yet. It would be good to wait for that until it gets official.
According to https://nodejs.org/en/about/releases/ node 10 will be there for a year or two so it would be good to keep supporting it (with a variant).

**Comment by merlinschumacher** [comment]
The new version is based on Node.js 10. There is also a variant with Node.js 12. The variants are documented in rhe README file now.
