### ISSUE TITLE
devel branch pulled by start.sh : question?

### ISSUE THREAD

**Issue by joerk** [ct-Open-Source/ct-Smart-Home#18]
Hi, 

today I started "./start.sh update" and a new docker image for ctnodered was pulled from the docker hub. 

I see there are commits in the devel branch (4 days ago) - these commits make trouble on my system Raspberry Pi. 

- Is ist normal and ok, that ./start.sh update pulled the changes from devel? 
- The change at docker-compose 
...
services:
  nodered:
    image: ctmagazin/ctnodered
.... to 
services:
  nodered:
    image: ctmagazin/ctnodered**:amd64-devel**

forces nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error" 

see docker-compose logs below 
-------snipp

pi@pi3:~/ct-Smart-Home $ ./start.sh update
Shutting down all running containers and removing them.
Stopping ct-smart-home_nodered_1 ... done
Stopping ct-smart-home_mqtt_1    ... done
Stopping ct-smart-home_zigbee_1  ... done
Removing ct-smart-home_nodered_1 ... done
Removing ct-smart-home_mqtt_1    ... done
Removing ct-smart-home_zigbee_1  ... done
Removing network ct-smart-home_default
Pulling current version via git.
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 14 (delta 2), reused 11 (delta 2), pack-reused 0
Entpacke Objekte: 100% (14/14), Fertig.
Von https://github.com/ct-Open-Source/ct-Smart-Home
   2ff0c3a..908e729  devel      -> origin/devel
Aktualisiere 2ff0c3a..908e729
Fast-forward
 README.md                         |  2 +-
 docker-compose.yml                |  8 ++---
 docker/ctnodered/Dockerfile       | 70 ++++++++++++++++++------------------
 docker/ctnodered/Dockerfile.arm   | 76 +++++++++++++++++++--------------------
 docker/ctnodered/entrypoint.sh    | 18 ++++++++++
 docker/ctnodered/supervisord.conf | 38 --------------------
 start.sh                          |  6 ++++
 7 files changed, 101 insertions(+), 117 deletions(-)
 create mode 100644 docker/ctnodered/entrypoint.sh
 delete mode 100644 docker/ctnodered/supervisord.conf
Pulling current images.
Pulling mqtt    ... done
Pulling nodered ... done
Pulling zigbee  ... done
Only starting the containers:

Starting the containers
CPU architecture is: arm
Creating network "ct-smart-home_default" with the default driver
Creating ct-smart-home_zigbee_1 ... done
Creating ct-smart-home_mqtt_1   ... done
Creating ct-smart-home_nodered_1 ... done
pi@pi3:~/ct-Smart-Home $ docker-compose logs
Attaching to ct-smart-home_nodered_1, ct-smart-home_mqtt_1, ct-smart-home_zigbee_1
nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error"
nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error"
nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error"
nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error"
nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error"
nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error"
nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error"
nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error"
nodered_1  | standard_init_linux.go:207: exec user process caused "exec format error"

**Comment by sjewo** [comment]
I had to change `image: ctmagazin/ctnodered:amd64-devel` to `image: ctmagazin/ctnodered:arm32v7` to make it work on my raspberry pi b+.

**Comment by merlinschumacher** [comment]
The devel branch will always contain unstable and possibly broken changes. But this is fixed now with the latest commit.
