### ISSUE TITLE
Javascript: neuere Version?

### ISSUE THREAD

**Issue by dmenne** [ct-Open-Source/ct-Smart-Home#19]
Gibt es Gründe, warum javascript bei der Version 8.x bleibt? Siehe auch:

https://github.com/c5te1n/node-red-contrib-dwd-local-weather/issues/8

**Comment by merlinschumacher** [comment]
Die nächste Fassung wird auf dem neuen offiziellen Node-Red 1.0 Docker-Image basieren. Das gibt es sowohl mit NodeJS 10 als auch 12. Das Image hier wird dann nur noch ein paar Modifikationen in Form von Nodes aus c't-Artikeln zum Image hinzufügen.

**Comment by dmenne** [comment]
Ok, habe gerade das devel runtergeladen. Vielleicht in diesem Zusammenhang auch korrigieren, dass es im help "start.sh" heißt, aber setup.sh heißen sollte. Ging mir so oft daneben, dass  eine Kopie gemacht habe, damit beides geh.t

**Comment by merlinschumacher** [comment]
Die neue basiert auf Node.js 10. Optional gibt es eine Variante für Version 12.
