### ISSUE TITLE
Mosquitto not starting

### ISSUE THREAD

**Issue by fischkai** [ct-Open-Source/ct-Smart-Home#21]
I installed the ct-smart-home project as described on a raspberry pi with buster lite.
Mosquitto does not seem to start.
The zigbee2mqtt log says:
error 2019-12-28 18:10:46: Cannot send message: topic: 'zigbee2mqtt/bridge/log', payload: '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x0017880106362a8a","model":"324131092621","vendor":"Philips","description":"Hue dimmer switch","supported":true}}
info  2019-12-28 18:10:46: Configuring '0x0017880106362a8a'
error 2019-12-28 18:10:49: Not connected to MQTT server!
info  2019-12-28 18:10:49: Succesfully configured '0x0017880106362a8a'
error 2019-12-28 18:10:59: Not connected to MQTT server!
error 2019-12-28 18:11:09: Not connected to MQTT server!

Any idea?

Best Regards
Kai

**Comment by merlinschumacher** [comment]
Are there any logs from the mosquitto server?
