### ISSUE TITLE
Privileged and Capabilities in docker-compose file

### ISSUE THREAD

**Issue by siredmar** [ct-Open-Source/ct-Smart-Home#23]
Please check your docker-compose file: https://github.com/ct-Open-Source/ct-Smart-Home/blob/1e37ed33c9faab3a1d1a9ab1278450bc656215b0/docker-compose.yml#L13-L16

It seems you have some redundant settings. I also recommend not running the container privileged unless really, really needed. In most cases you can achieve the wanted effect by adding some capabilities and mounts for your specific needs.

**Comment by merlinschumacher** [comment]
The container now runs non priviledged. Thanks for the tipp!
