### ISSUE TITLE
why user 1001 instead of 1000?

### ISSUE THREAD

**Issue by Bigfoot611** [ct-Open-Source/ct-Smart-Home#29]
Hi,
setup works like a charm, but there is one point I don't understand.
Original nodered/node-red container works with user 1000 and also here:
node-red: x :1000:1000:Linux User,,,:/usr/src/node-red:/bin/ash

So why chown with user and group 1001:1001?

I would very happy if anybody can explain... thanks.

**Comment by merlinschumacher** [comment]
That is a bug. I will fix it with the next version.
