### ISSUE TITLE
documentation: setup.sh => start.sh 

### ISSUE THREAD

**Issue by joerk** [ct-Open-Source/ct-Smart-Home#3]
Hi, minor issue for documentation 

seems that you renamed the setup.sh to start.sh and didn't update the documentation and script help . Might confuse some c't reader - sure not the iX ones. 

**start.sh** options

c't-Smart-Home – setup script                                                                                                                             
=============================
Usage:
**setup.sh** update – to update to this copy of the repo
setup.sh start – run all containers
setup.sh stop – stop all containers
setup.sh data – set up the data folder needed for the containers, but run none of them. Useful for personalized setups.   Regards Jörk

**Comment by jamct** [comment]
fixed by #5
