### ISSUE TITLE
Node-Red Password einrichten

### ISSUE THREAD

**Issue by Pretoryus** [ct-Open-Source/ct-Smart-Home#33]
Hallo ich habe den Artikel in der CT gelesen wie ich das Dashboard mit einem Passwort absichern kann.
Wie ist es möglich in den Container von Node Red ein Terminal zu öffnen und die Einrichtuing vorzunehmen.
Dies ist meine erste erfahrung mit Docker.
Vielen Dank

**Comment by merlinschumacher** [comment]
Hallo Pretoryus, 

es reicht, wenn Sie in den Ordner `data/nodered` wechseln. Dort finden Sie die `settings.js`, in der Sie die nötigen Einstellungen vornehmen können. Nach einem Neustart des Node-Red-Containers mit `docker-compose restart nodered` sollte das Dashboard geschützt sein.
