### ISSUE TITLE
Add HTTPS for NodeRed (+Mosquitto)

### ISSUE THREAD

**Issue by KarstenDE** [ct-Open-Source/ct-Smart-Home#36]
From my point of view it would be interesting to integrate HTTPS with LetsEncrypt to the NodeRed Container. Possibly additional for Mosquitto.
What would be the right approach here?

Traefik? Or is it possible to issue and integrate the certificates directly into NodeRed?

Based on the situation that this smarthome components should not be available from the Internet, the DNS-challenge option of LetsEncrypt would be interesting.

Would be interesting to have it included into docker-compose file here.

**Comment by abmurksi** [comment]
I would argue that this is out of scope for this starter smarthome repo.
Maybe enabling https for mqtt and NR with selfsigned certificates might be enough?

**Comment by merlinschumacher** [comment]
Traefik would be a viable solution, but implementing it would be overkill for this project and might bring a lot of issues for entry level users.
