### ISSUE TITLE
Cannot access Zigbee administrative interface

### ISSUE THREAD

**Issue by ceysa75** [ct-Open-Source/ct-Smart-Home#37]
Dear ct Team,

Thanks for your explanations which, however, slightly differ from the way as explained in the magazine. Finally - as a total noob in the linux and node red world the installation was successful. However, for some reason accessing the Zigbee administrative interface (Zigbee2MqttAssistant) is not possible. I tried it with http://IPraspberry:8880. But starting node red with http://IPraspberry:1880 works. Is this related with the configuration.yaml file which actually is not fully configured after a fresh install.

I think, I need the Zigbee administrative interface for basic stuff like simply pairing devices, am I right ? Unfortunately, in your magazine it is not described how to simply pair the CC2531 USB sniffer and a simple zigbee device as e.g. a a power plug (in my case the Innr SP 220).

Best regards...

**Comment by ceysa75** [comment]
Dear ct team,

I am really struggling with the pairing process. What I think I have learned now is that pairing should be possible directly within the Node Red interface. As far as I understood I need 'node-red-contrib-zigbee' for that. However, it cannot be installed for whatever reason. While downloading and installing other other contribs this one in particular cannot be installed. The respective LOG report reveals a lot of errors...
I really need your support with my general pairing issues.

Regards

Ceysa

**Comment by merlinschumacher** [comment]
The zigbee interface will be changed to the native one provided by zigbee2mqtt. Read more about it here: https://www.zigbee2mqtt.io/information/frontend.html
It will be available on port 1881. You can check out the latest master to test it.
