### ISSUE TITLE
possible compose file error:     network_mode: "host"

### ISSUE THREAD

**Issue by Leinetaler** [ct-Open-Source/ct-Smart-Home#40]
Hi 
many thanks for this interesting project, which encourage me to give it a try ....

Following the instructions i was not able to start the containers.

routecause:

Compose file line 14:     network_mode: "host"

The error message point out that host mode is not compatible with port bindings.

Delete the line will fix the problem as the standart network mode will work.

hope this may help other to get started,

sunny regards

**Comment by merlinschumacher** [comment]
This indeed was a mistake in the file. It's fixed in the master now.

**Comment by Leinetaler** [comment]
Hi,
in actual version 3.6 of docker-compose.yml, seems that network_mode:"host" entry is back. now in line 12.

This does not match the descriction of changes - see fixed issue #40.

Sunny regards
