### ISSUE TITLE
Please more documentation / a sample configuration

### ISSUE THREAD

**Issue by jazzcrack** [ct-Open-Source/ct-Smart-Home#7]
I tryed to start the docker on a Raspberry Pi with Raspbian Stretch/Hypriotos and run every time into strange problems with starting all dockers. A tested Raspberry Pi sample configuration with less problems would be nice.

**Comment by merlinschumacher** [comment]
Could you give me more detailed infos on what problems you experience? I have this setup running on my raspberry pi on stretch.

**Comment by jazzcrack** [comment]
Revision 2 of Raspberry Pi Model B with Raspbian Stretch/Hypriotos failed every time. Maybe my Raspberry Pi is too old?

**Comment by merlinschumacher** [comment]
The raspberry pi 2 should work. I always use Raspbian as the basis and never tried hypriot. Is there a notable error message?
