### ISSUE TITLE
Fatal error after updating from nodered v2.0.6 (unreachable code in line 0 #failuremessage object: 0x7ec6023c illegal instruction) 

### ISSUE THREAD

**Issue by KaHeMu** [ct-Open-Source/ct-Smart-Home#72]
Hello, 

after updating my system via ./start.sh update nodered doesn't start anymore and reports the following error (zigbee2mqtt and mqtt updated well):
```
fatal error in , line 0 
#unreachable code 
#failuremessage object: 0x7ec6023c 
illegal instruction

```
Any idea what the root cause might be? 

(Sorry I'm new to github and docker)
Thanks!

**Comment by 8xiom** [comment]
Most likely related to https://github.com/ct-Open-Source/ct-Smart-Home/issues/70.

**Comment by KaHeMu** [comment]
Correct. I found the rollback workaround mentioned in [#70](https://github.com/ct-Open-Source/ct-Smart-Home/issues/70)   by myself and it works well. But unfortunately, this is NOT a fix of the issue with the latest image which still needs to be solved. But I close this issue.
